language: ruby
rvm:
 - 2.3.7
before_script:
 - psql -c 'create database "demo-deploy_test";' -U postgres
script:
 - RAILS_ENV=test bin/rails db:migrate --trace
 - bundle exec rspec
deploy:
  provider: heroku
  app: devops-cert-activity-wilsonmar
  api_key:
    secure: $HEROKU_API_KEY
  run: "rails db:migrate"